### PR TITLE
Add Andrey's submission

### PR DESCRIPTION
**Pull request by dendibakh**

### CODE REVIEW

**Comment by dendibakh** [comment]
@ibogosavljevic, we can add/ask others to add their submission here, what you think?

**Comment by ibogosavljevic** [comment]
Yes, we should do that. There were some really nice ideas there

**Comment by freetomik** [comment]
This is excellent work, @andrewevstyukhin 👌
Lots of optimization techniques to learn from, and commit descriptions with times are very clear to read and helpful. Thanks for sharing!

**Comment by andrewevstyukhin** [comment]
You'll be surprised, but I've being learning too. Loop interchange is not so hard but very efficient optimization technique for memory-bound algorithms. Intrinsics are not always helpful.

**Comment by freetomik** [comment]
I think there is always room to learn something new in this area - modern processors are so complex and the industry is still evolving. I have done both techniques at work, and I agree. Today compilers can vectorize code quite well, so often manual vectorization with intrinsics does not help so much. But memory access patterns on images are good places for improvements.

**Pull request merged**
