### PR TITLE
Add Tomas Hudziec submission

### PR DESCRIPTION
**Pull request by freetomik**
Steps of optimization:
1. two loop interchanges with using row dot & sum buffers in gaussian bluring in the Y direction
2. loop interchange in making derivative in the Y direction

### CODE REVIEW

**Comment by dendibakh** [comment]
@freetomik , you already uploaded your submission here: https://github.com/dendibakh/perf_challenge4/pull/10. Is it a different set of patches?

**Comment by freetomik** [comment]
@dendibakh , oh, the issue #10 was meant to be only that fix in run.py. Somehow unintentionally I added my other commits to it (but the last one is missing). Sorry for confusion, this #12 is my final submission.

**Comment by dendibakh** [comment]
> @dendibakh , oh, the issue #10 was meant to be only that fix in run.py. Somehow unintentionally I added my other commits to it (but the last one is missing). Sorry for confusion, this #12 is my final submission.

I see, so please rebase this PR on top of the current top of the tree.

**Comment by freetomik** [comment]
Ok, now it should be correct, hopefully :)

**Pull request merged**
